import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Euphoria Travels",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased bg-pine/5 bg-[url('/images/bg-pattern.png')] bg-fixed bg-cover bg-center bg-no-repeat`}>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
